name: Release OSS (APK)

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false
          dotnet: true
          haskell: true
          large-packages: true

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.35.2

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: Get Packages
        run: flutter pub get

      - name: Generate Localization Dart Files
        run: flutter gen-l10n

      - name: Commit generated Arabic localization support
        run: |
          git config --global user.name "Maher"
          git config --global user.email "actions@github.com"

          git add lib/l10n/*.dart
          git add lib/generated/**/*.dart || true

          if ! git diff --cached --quiet; then
            git commit -m "feat(l10n): add professional Arabic language support and generated localization files"
            git push
          fi

      - name: Generate Rust
        run: flutter_rust_bridge_codegen generate

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29-beta4

      - uses: SimonMarquis/android-accept-licenses@v1

      - name: Build Release APKs
        run: flutter build apk --release --split-per-abi

      - name: Upload Localization Dart Artifact
        uses: actions/upload-artifact@v7
        with:
          name: generated-arabic-localization
          path: |
            lib/l10n/*.dart
            lib/generated/**/*.dart

      - name: Upload Release APK Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts
          path: build/app/outputs/flutter-apk/*release*.apk